config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: 'dev' do
    get '/' => redirect { |params| "almapp.github.io" } #TODO redirect to github
  end

  constraints(Subdomain) do
    get '/' => 'organizations#show'

    resources :faculties, shallow: true do
      resources :academic_unities
      resources :careers
      resources :courses
      resources :teachers
    end

    resources :camps do
      resources :places, except: [:maps]
    end
    resources :places, only: [:maps]

    resources :users

    get 'maps', controller: 'maps', action: 'index'

    devise_for :users, path: "",
               controllers: { sessions: "users/sessions",
                              registrations: 'users/registrations'},
               path_names: { sign_in: 'login',
                             password: 'forgot',
                             confirmation: 'confirm',
                             unlock: 'unblock',
                             sign_up: 'register',
                             sign_out: 'signout'}
  end

  resources :groups
  resources :organizations
  resources :events

  root 'organizations#index'

end

app/views/layouts/uc/_alerts.html.erb
<% flash.each do |name, msg| %>
    <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
    <% end %>
<% end %>

app/views/layouts/uc/_header.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= favicon_link_tag 'uc_favicon.ico' %>
  <title><%= yield(:title).present? ? (yield(:title)+ ' - ') : ''%>/Almapp <%= current_subdomain.upcase %></title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= yield :css %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>


  <%= yield :js %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= csrf_meta_tags %>
</head>

app/views/layouts/uc/_navbar.html.erb
<!-- https://github.com/seyhunak/twitter-bootstrap-rails -->
<%= nav_bar :fixed => :top, :brand => 'Almapp ' + current_organization.slug, :responsive => true, :brand_link => root_url(subdomain: '') do %>
    <%= menu_group do %>
        <%= menu_item 'Home', root_path %>
        <%= menu_divider %>
        <%= drop_down 'Campus' do %>
            <% current_organization.camps.order(:name).each do |camp| %>
                <%= menu_item camp.name, camp_path(camp) %>
            <% end %>
        <% end %>
        <%= drop_down 'Faculties' do %>
            <% current_organization.faculties.order(:short_name).each do |faculty| %>
                <%= menu_item faculty.short_name, faculty_path(faculty) %>
            <% end %>
        <% end %>
        <%= menu_divider %>
        <%= menu_item 'Maps', maps_path %>
        <%= menu_divider %>
        <%= menu_item 'Events', events_path %>
        <%= menu_divider %>
        <%= menu_item 'Users', users_path %>
        <%= menu_divider %>
        <%= menu_item 'Groups', groups_path %>
    <% end %>
    <%= menu_group :pull => :right do %>
        <% if user_signed_in? %>
            <%= menu_text current_user.slug %>
            <%= menu_item "Log Out", destroy_user_session_path(user_session), :method=> :delete %>
        <% else %>
            <%= form_for(:user, :url => user_session_path(user_session), html: { class: "navbar-form navbar-right form-inline" }) do |f| %>
                <div class="form-group">
                  <%= f.text_field :email, :placeholder => "Email", class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.password_field :password, :placeholder => "Password", class: "form-control"  %>
                </div>
                <%= f.submit 'Login', class: "btn btn-default" %>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/uc/application.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/uc/header' %>
<body>

<%= render 'layouts/uc/navbar' %>

<div class="container">

  <%= render 'layouts/uc/alerts' %>

  <%= yield %>

</div>
</body>
</html>

app/views/layouts/uc/full_screen.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/uc/header' %>
<body>

<%= render 'layouts/uc/navbar' %>

<div class="container">

  <%= render 'layouts/uc/alerts' %>

  <%= yield %>

</div>
</body>
</html>