config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: 'dev' do
    get '/' => redirect { |params| "almapp.github.io" } #TODO redirect to github
  end

  constraints(Subdomain) do
    get '/' => 'organizations#show'

    resources :faculties, shallow: true do
      resources :academic_unities
      resources :careers
      resources :courses
      resources :teachers
    end

    resources :camps do
      resources :places, except: [:maps]
    end
    resources :places, only: [:maps]

    resources :users

    get 'maps', controller: 'maps', action: 'index'

    devise_for :users, path: "",
               controllers: { sessions: "users/sessions",
                              registrations: 'users/registrations'},
               path_names: { sign_in: 'login',
                             password: 'forgot',
                             confirmation: 'confirm',
                             unlock: 'unblock',
                             sign_up: 'register',
                             sign_out: 'signout'}
  end

  resources :groups
  resources :organizations
  resources :events

  root 'organizations#index'

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)      not null
#  url             :string(255)
#  facebook        :string(255)
#  twitter         :string(255)
#  information     :text
#  expiration      :date
#  organization_id :integer
#  created_at      :datetime
#  updated_at      :datetime
#  faculty_id      :integer
#  slug            :string(255)
#

class Group < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true, format: /\A[a-z0-9]+[a-z0-9\._-]*@[a-z0-9\.]+\.[a-z]{2,5}\z/i
  validates :name, presence: true
  validates :expiration, presence: true
  validates :organization, presence: true
  validates :faculty_id, inclusion: { in: ->(record) { record.organization.faculties } } #TODO Testing

  belongs_to :organization
  belongs_to :faculty

  has_many :published_posts, source: :poster_group, class_name: 'Post'

  has_many :groups_admins
  has_many :admins, through: :groups_admins, source: :user

  has_many :groups_subscribers
  has_many :subscribers, through: :groups_subscribers, source: :user

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged # you must do User.friendly.find('foo')

  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
    :name,
    [:name, :id],
    ]
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = current_organization.groups
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :email, :url, :facebook, :twitter, :information, :expiration, :organization_id, :faculty_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= bootstrap_form_for(@group, layout: :horizontal) do |f| %>
    <%= f.text_field :name %>
    <%= f.email_field :email %>
    <%= f.url_field :url %>
    <%= f.url_field :facebook %>
    <%= f.url_field :twitter %>
    <%= f.text_area :information %>
    <%= f.date_field :expiration %>
    <%= f.select :organization_id, options_for_select(Organization.all.order('name').map{ |c| [c.name, c.id]}, selected_key = f.object.organization_id)%>
    <%= f.select :faculty_id, options_for_select(Faculty.all.order('short_name').map{ |c| [c.short_name, c.id]}, selected_key = f.object.faculty_id), include_blank: '-- Select a Faculty --' %>

    <%= f.form_group do %>
        <%= f.submit %>
    <% end %>
<% end %>

app/views/groups/edit.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:organization) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:facebook) %></th>
      <th><%= model_class.human_attribute_name(:twitter) %></th>
      <th><%= model_class.human_attribute_name(:information) %></th>
      <th><%= model_class.human_attribute_name(:expiration) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.id, group_path(group) %></td>
        <td><%= link_to group.name, group_path(group) %></td>
        <td><%= link_to group.organization.name, organization_path(group.organization)  %></td>
        <td><%= group.email %></td>
        <td><%= group.url %></td>
        <td><%= group.facebook %></td>
        <td><%= group.twitter %></td>
        <td><%= group.information %></td>
        <td><%= group.expiration %></td>
        <td><%=l group.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_group_path(group), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      group_path(group),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_group_path,
            :class => 'btn btn-primary' %>

app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/show.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @group.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:organization) %>:</strong></dt>
  <dd><%= link_to @group.organization.name, organization_path(@group.organization)  %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @group.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @group.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:facebook) %>:</strong></dt>
  <dd><%= @group.facebook %></dd>
  <dt><strong><%= model_class.human_attribute_name(:twitter) %>:</strong></dt>
  <dd><%= @group.twitter %></dd>
  <dt><strong><%= model_class.human_attribute_name(:information) %>:</strong></dt>
  <dd><%= @group.information %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expiration) %>:</strong></dt>
  <dd><%= @group.expiration %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              groups_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_group_path(@group), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              group_path(@group),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>