config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: 'dev' do
    get '/' => redirect { |params| "almapp.github.io" } #TODO redirect to github
  end

  constraints(Subdomain) do
    get '/' => 'organizations#show'

    resources :faculties, shallow: true do
      resources :academic_unities
      resources :careers
      resources :courses
      resources :teachers
    end

    resources :camps do
      resources :places, except: [:maps]
    end
    resources :places, only: [:maps]

    resources :users

    get 'maps', controller: 'maps', action: 'index'

    devise_for :users, path: "",
               controllers: { sessions: "users/sessions",
                              registrations: 'users/registrations'},
               path_names: { sign_in: 'login',
                             password: 'forgot',
                             confirmation: 'confirm',
                             unlock: 'unblock',
                             sign_up: 'register',
                             sign_out: 'signout'}
  end

  resources :groups
  resources :organizations
  resources :events

  root 'organizations#index'

end

app/models/academic_unity.rb
# == Schema Information
#
# Table name: academic_unities
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  faculty_id  :integer
#  slug        :string(255)      not null
#  url         :string(255)
#  email       :string(255)
#  address     :string(255)
#  information :text
#  facebook    :string(255)
#  twitter     :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  short_name  :string(255)      not null
#

class AcademicUnity < ActiveRecord::Base
  validates :short_name, presence: true
  validates :faculty_id, presence: true

  belongs_to :faculty

  has_many :teachers
  has_many :courses
  has_many :careers

  extend FriendlyId
  friendly_id :short_name, use: :scoped, scope: :faculty # http://www.rubydoc.info/github/norman/friendly_id/FriendlyId/Scoped

end

app/controllers/academic_unities_controller.rb
class AcademicUnitiesController < ApplicationController
  before_action :set_academic_unity, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @academic_unities = AcademicUnity.all
    respond_with(@academic_unities)
  end

  def show
    respond_with(@academic_unity)
  end

  def new
    @academic_unity = AcademicUnity.new
    respond_with(@academic_unity)
  end

  def edit
  end

  def create
    @academic_unity = AcademicUnity.new(academic_unity_params)
    @academic_unity.save
    respond_with(@academic_unity)
  end

  def update
    @academic_unity.update(academic_unity_params)
    respond_with(@academic_unity)
  end

  def destroy
    @academic_unity.destroy
    respond_with(@academic_unity)
  end

  private
    def set_academic_unity
      @academic_unity = AcademicUnity.find(params[:id])
    end

    def academic_unity_params
      params.require(:academic_unity).permit(:name, :faculty_id, :url, :email, :address, :information, :facebook, :twitter)
    end
end

app/helpers/academic_unities_helper.rb
module AcademicUnitiesHelper
end

app/views/academic_unities/_form.html.erb
<%= form_for(@academic_unity, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @academic_unity.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@academic_unity.errors.count, "error") %> prohibited this academic_unity from being saved:</h4>

      <ul>
      <% @academic_unity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :faculty, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :faculty, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :information, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :information, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :facebook, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :facebook, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :twitter, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :twitter, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/academic_unities/edit.html.erb
<div class="page-header">
  <%= link_to academic_unities_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @academic_unity, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing academic_unity</h1>
</div>

<%= render 'form' %>

app/views/academic_unities/index.html.erb
<div class="page-header">
  <%= link_to new_academic_unity_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Academic unity
  <% end %>
  <h1>Listing academic_unities</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Faculty</th>
            <th>Url</th>
            <th>Email</th>
            <th>Address</th>
            <th>Information</th>
            <th>Facebook</th>
            <th>Twitter</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @academic_unities) do |academic_unity| %>
            <td><%= academic_unity.name %></td>
            <td><%= academic_unity.faculty %></td>
            <td><%= academic_unity.url %></td>
            <td><%= academic_unity.email %></td>
            <td><%= academic_unity.address %></td>
            <td><%= academic_unity.information %></td>
            <td><%= academic_unity.facebook %></td>
            <td><%= academic_unity.twitter %></td>
            <td><%= link_to 'Show', academic_unity %></td>
        <td><%= link_to 'Edit', edit_academic_unity_path(academic_unity) %></td>
        <td><%= link_to 'Destroy', academic_unity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/academic_unities/new.html.erb
<div class="page-header">
  <%= link_to academic_unities_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New academic_unity</h1>
</div>

<%= render 'form' %>

app/views/academic_unities/show.html.erb
<div class="page-header">
  <%= link_to academic_unities_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_academic_unity_path(@academic_unity), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show academic_unity</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @academic_unity.name %></dd>

  <dt>Faculty:</dt>
  <dd><%= @academic_unity.faculty %></dd>

  <dt>Url:</dt>
  <dd><%= @academic_unity.url %></dd>

  <dt>Email:</dt>
  <dd><%= @academic_unity.email %></dd>

  <dt>Address:</dt>
  <dd><%= @academic_unity.address %></dd>

  <dt>Information:</dt>
  <dd><%= @academic_unity.information %></dd>

  <dt>Facebook:</dt>
  <dd><%= @academic_unity.facebook %></dd>

  <dt>Twitter:</dt>
  <dd><%= @academic_unity.twitter %></dd>

</dl>