config/routes.rb
Rails.application.routes.draw do

  constraints subdomain: 'dev' do
    get '/' => redirect { |params| "almapp.github.io" } #TODO redirect to github
  end

  constraints(Subdomain) do
    get '/' => 'organizations#show'

    resources :faculties, shallow: true do
      resources :academic_unities
      resources :careers
      resources :courses
      resources :teachers
    end

    resources :camps do
      resources :places, except: [:maps]
    end
    resources :places, only: [:maps]

    resources :users

    get 'maps', controller: 'maps', action: 'index'

    devise_for :users, path: "",
               controllers: { sessions: "users/sessions",
                              registrations: 'users/registrations'},
               path_names: { sign_in: 'login',
                             password: 'forgot',
                             confirmation: 'confirm',
                             unlock: 'unblock',
                             sign_up: 'register',
                             sign_out: 'signout'}
  end

  resources :groups
  resources :organizations
  resources :events

  root 'organizations#index'

end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id          :integer          not null, primary key
#  name        :string(255)      not null
#  information :text
#  image       :string(255)
#  url         :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  facebook    :string(255)
#  twitter     :string(255)
#  slug        :string(255)      not null
#

class Organization < ActiveRecord::Base
  validates :name, presence: true
  validates :slug,
            presence: true,
            uniqueness: true,
            exclusion: { in: %w(www mail ftp dev help), message: '%{value} is reserved.' },
            format: { with: /\A(?=.*[a-z])[a-z\d]+\Z/i, message: 'incorrect format' }

  has_many :users, class_name: 'User'
  has_many :groups

  has_many :camps
  has_many :faculties, through: :camps
  has_many :academic_unities, through: :faculties

  has_many :places, through: :camps
  has_many :careers, through: :academic_unities
  has_many :courses, through: :academic_unities
  has_many :teachers, through: :academic_unities

  has_many :published_posts, source: :poster_organization, class_name: 'Post'

  has_many :organization_admins
  has_many :admins, through: :organization_admins, source: :user

  def add_admin(user)
    OrganizationAdmin.create!(organization: self, user: user)
  end

  def self.find_with_subdomain(subdomain)
    self.where("lower(slug) = ?", subdomain.downcase).first if (subdomain.present? && subdomain.size != 0)
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_path, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      if params[:id]
        @organization = Organization.find(params[:id])
      else
        @organization = current_organization
      end

      if @organization.present?
        @organization
      else
        redirect_to root_url(subdomain: '')
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :slug, :information, :image, :url, :twitter, :facebook)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= bootstrap_form_for(@organization, layout: :horizontal) do |f| %>
    <%=f.text_field :name %>
    <%=f.url_field :url %>
    <%=f.url_field :facebook %>
    <%=f.url_field :twitter %>
    <%=f.text_area :information %>

    <%= f.form_group do %>
        <%= f.submit %>
    <% end %>
<% end %>

app/views/organizations/edit.html.erb
<%- model_class = Organization -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/organizations/index.html.erb
<%- model_class = Organization -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:information) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= link_to organization.id, root_url(subdomain: get_subdomain_for_organization(organization)) %></td>
        <td><%= link_to organization.name, root_url(subdomain: get_subdomain_for_organization(organization)) %></td>
        <td><%= organization.information %></td>
        <td><%= organization.image %></td>
        <td><%= organization.url %></td>
        <td><%=l organization.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_organization_path(organization), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      organization_path(organization),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_organization_path,
            :class => 'btn btn-primary' %>

app/views/organizations/new.html.erb
<%- model_class = Organization -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/organizations/show.html.erb
<%- model_class = Organization -%>
<div class="jumbotron">
  <h1><%= @organization.name %></h1>
  <p><%#= link_to 'View', root_url(subdomain: get_subdomain(@organization)), class: 'btn btn-primary btn-lg' %> </p>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= link_to @organization.url, @organization.url.to_s %></dd>
  <dt><strong><%= model_class.human_attribute_name(:facebook) %>:</strong></dt>
  <dd><%= link_to @organization.facebook, @organization.facebook.to_s %></dd>
  <dt><strong><%= model_class.human_attribute_name(:twitter) %>:</strong></dt>
  <dd><%= link_to @organization.twitter, @organization.twitter.to_s %></dd>
  <dt><strong><%= model_class.human_attribute_name(:information) %>:</strong></dt>
  <dd><%= @organization.information %></dd>
</dl>

<div class="page-header">
  <h2>Campus</h2>
</div>

<div class="list-group">
  <% @organization.camps.order('id asc').each do |camp| %>

      <%= link_to camp_url(camp, subdomain: get_subdomain_for_organization(@organization)), class: 'list-group-item' do %>
          <h4 class="list-group-item-heading"><%= camp.name %></h4>
          <p class="list-group-item-text"><%= camp.description %></p>
      <% end %>

  <% end %>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              organizations_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_organization_path(@organization), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              organization_path(@organization),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>